version: '3.8'

networks:
  order_network:   # Nome da rede personalizada
    driver: bridge  # Pode ser 'bridge', 'overlay', etc.

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eclipseworks-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    networks:
      - order_network   # Conecta o serviço à rede personalizada

  database:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=offer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@OfferAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order_network   # Conecta o serviço à rede personalizada

volumes:
  postgres_data: